#TAREA 1# 
#SARA DEL SOCORRO ROBLES ORTIZ# 
library(Biostrings)
seq1<-readRNAStringSet("secuencia.fasta")
seq1
translate(seq1)
seq2<-DNAString("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")
seq2 #CREAR OBJETO Y DESPUÉS CREAR EL PROGRAMA PARA VER COMO FUNCIONA UNA VEZ QUE SE TIENE LA SECUENCIA DESEADA# 
#Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.#
##CON LIBRERÍAS ESPECIALIZADAS## 
alphabetFrequency(seq2, as.prob=TRUE)
uniqueLetters(seq2)
view.width <- 70 #CON ESTE OBJETO SE ESTABLECE EL TAMAÑO DE LA SECUENCIA PARA QUE DESPUÉS SE PUEDAN CONTAR LOS NUCLEÓTIDOS 
letters<-c ("A", "G", "C", "T")# ESTE OBJETO PERMITE ESTABLECER LOS NUCLEÓTIDOS QUE INTERESAN 
col<-letterFrequencyInSlidingView(seq2, view.width, letters)# ARROJA EL NÚMERO QUE PERTENECE A CADA NUCLEÓTIDO POR LA SECUENCIA DE INTERÉS 
col
#CON PROGRAMA# 
secuencia<-"AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
sec<-substr(secuencia, 0, 70)#SELECCIONA ÚNICAMENTE DE DÓNDE A DÓNDE QUIERES QUE SE HAGA LA FUNCIÓN 
secuencia2<- strsplit(secuencia, "") #SEPARA LA SECUENCIA EN ARGUMENTOS INDIVIDUALES 
secuencia3<-unlist(secuencia2)
conteo<-table(secuencia3)#LO PONE EN FORMATO DE TABLA 
conteo #CUENTA EL NÚMERO DE NT EN LA CADENA DE INTERÉS 
dna<-strsplit(secuencia, split="")#SEPARA POR CARACTERES LAS LETRAS DE LA SECUENCIA METIDAS ANTERIORMENTE 
dna
A<-0 #OBJETOS CREADOS PARA CADA UNA DE LAS BASES 
T<-0 #OBJETOS CREADOS PARA CADA BASE 
C<-0 #OBJETO PARA CADA BASE 
G<-0 #OBJETO PARA CADA BASE 
count <- A+C+T+G #FORMA PARTE DE LO QUE SE METERÁ A LA FUNCIÓN. PARA HACER EL CONTEO DE NUCLEÓTIDOS 
while (count < 20) {
  DNA_A <- gsub("A","",dna)
  A <- nchar(dna)-nchar(DNA_A)
  print("A")
  print(A)
  DNA_C <- gsub("C","",dna)
  C <- nchar(dna)-nchar(DNA_C)
  print("C") 
  print(C)
  DNA_G <- gsub("G","",dna)
  G <- nchar(dna)-nchar(DNA_G)
  print("G") 
  print(G)
  DNA_T <- gsub("T","",dna)
  T <- nchar(dna)-nchar(DNA_T)
  print("T") 
  print(T)
  count = A+C+T+G
}
#EL PROGRAMA TIENE COMO OBJETIVO CONTAR EL NÚMERO TOTAL DE CADA NUCLEÓTIDO. UTILICÉ LA FUNCIÓN WHILE, AUNQUE AL INICIO SE ME HIZO UN BUCLE INFINITO 
# ANTES DE CREAR EL BUCLE CREE UN OBJETO DONDE SE FUERAN ALMACENANDO LOS CONTEOS. ENCONTRÉ EL ELEMENTO gsub QUE POR LO QUE ENTENDÍ PERMITE SELECCIONAR UN CARACTER Y CAMBIARLO POR OTRO ACORDE 
#EN ESTE CASO LO UTILICE PARA CONTABILIZAR CADA NUCLEÓTIDO AL SUSTITUIR EL NUCLEÓTIDO DESEADO POR UN "" Y DESPUÉS LO QUE HICE FUE HACER UNA RESTA DEL NÚMERO DE CARACTERES ORIGINALES CON EL NÚMERO DE CARACTERES FALTANTES 
#FINALMENTE IMPRIMÍ CADA BASE NITROGENADA 


 
#####EJERCICIO 2#########
seq3<-DNAString("CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG")
seq3#PRIMERO HICE DNA STRING INDIVIDUAL PARA OBSERVAR OMO SE COMPORTABA DE FORMA INDIVIDUAL 
letterFrequency(seq3, "GC", as.prob=TRUE)#SAQUÉ LA FRECUENCIA DE GC DE CADA SECUENCIA 
seq4<-DNAString("CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT")
seq4
letterFrequency(seq4,"GC", as.prob = TRUE)
seq5<- DNAString("CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC")
seq5
letterFrequency(seq5,"GC",as.prob=TRUE)
set<- DNAStringSet(c("CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG",
                     "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT",
                     "CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC"))
set#LUEGO PARA QUE ÚNICAMENTE ARROJARA LA SECUENCIA DE INTERÉS HICE UN STRING SET CON LAS SECUENCIAS. 
gc_content<-letterFrequency(set,"GC", as.prob = TRUE)
gc_content#SAQUÉ LA FRECUENCIA DE GC POR TODO EL SET 
max_gc_content<-set[which(gc_content==max(gc_content))]
max_gc_content #PARA DETERMINAR CUÁL TIENE EL MÁXIMO CONTENIDO DE GC 
content<-letterFrequency(max_gc_content, "GC", as.prob=TRUE)
content*100#MUESTRA EL PORCENTAJE DE GC DE LA SECUENCIA CON MÁS CONTENIDO DE GC  

#CON PROGRAMA# 
set
strsplit(set, "")
#TENGO LA IDEA DE CÓMO HACERLA, PERO NO ME ACUERDO BIEN. PREFIERO ENTREGARLO AHORITA ASÍ, EN CASO DE QUE MAÑANA NO TENGA TIEMPO DE TERMINARLO 

