#TAREA 1# 
#SARA DEL SOCORRO ROBLES ORTIZ# 
library(Biostrings)
seq1<-readRNAStringSet("secuencia.fasta")
seq1
translate(seq1)
seq2<-DNAString("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")
seq2 #CREAR OBJETO Y DESPUÉS CREAR EL PROGRAMA PARA VER COMO FUNCIONA UNA VEZ QUE SE TIENE LA SECUENCIA DESEADA# 
#Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.#
##CON LIBRERÍAS ESPECIALIZADAS## 
alphabetFrequency(seq2, as.prob=TRUE)
uniqueLetters(seq2)
view.width <- 70 #CON ESTE OBJETO SE ESTABLECE EL TAMAÑO DE LA SECUENCIA PARA QUE DESPUÉS SE PUEDAN CONTAR LOS NUCLEÓTIDOS 
letters<-c ("A", "G", "C", "T")# ESTE OBJETO PERMITE ESTABLECER LOS NUCLEÓTIDOS QUE INTERESAN 
col<-letterFrequencyInSlidingView(seq2, view.width, letters)# ARROJA EL NÚMERO QUE PERTENECE A CADA NUCLEÓTIDO POR LA SECUENCIA DE INTERÉS 
col
#CON PROGRAMA# 
secuencia<-"AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
sec<-substr(secuencia, 0, 70)
secuencia2<- strsplit(secuencia, "")
secuencia3<-unlist(secuencia2)
conteo<-table(secuencia3)
conteo
##EJERCICIO 2##
seq3<-DNAString("CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG")
seq3
letterFrequency(seq3, "GC", as.prob=TRUE)
seq4<-DNAString("CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT")
seq4
letterFrequency(seq4,"GC", as.prob = TRUE)
seq5<- DNAString("CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC")
seq5
letterFrequency(seq5,"GC",as.prob=TRUE)
set<- DNAStringSet(c("CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG",
                     "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT",
                     "CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC"))
set
gc_content<-letterFrequency(set,"GC", as.prob = TRUE)
gc_content
max_gc_content<-set[which(gc_content==max(gc_content))]
max_gc_content
content<-letterFrequency(max_gc_content, "GC", as.prob=TRUE)
content
